backend:
  name: github
  repo: MulisWater/my-website
  branch: main

media_folder: "static/images"
public_folder: "/static/images"
media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "posts"
    label: "文章管理"
    files:
      - name: "posts-list"
        label: "所有文章"
        file: "posts.json"
        fields:
          - label: "文章列表"
            name: "body"
            widget: "list"
            fields:
              - {label: "标题", name: "title", widget: "string"}
              - {label: "日期", name: "date", widget: "datetime"}
              - {label: "正文", name: "content", widget: "text"}