backend:
  name: github
  repo: MulisWater/my-website
  branch: main

media_folder: "static/images"
public_folder: "/static/images"

collections:
  - name: "posts"
    label: "文章管理"
    files:
      - name: "posts-list"
        label: "所有文章"
        file: "posts.json"
        fields:
          - label: "文章列表"
            name: "body"
            widget: "list"
            summary: "{{fields.title}} ({{fields.date}})"
            fields:
              - {label: "ID", name: "id", widget: "number", default: 1, value_type: "int"}
              - {label: "标题", name: "title", widget: "string"}
              - {label: "日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
              - {label: "标签", name: "tags", widget: "list", default: ["生活"]}
              - {label: "摘要", name: "excerpt", widget: "text"}
              - {label: "正文", name: "content", widget: "text"}